### ISSUE TITLE
Saving function?

### ISSUE THREAD

**Issue by vilp** [HTV04/htv04.github.io#15]
Can you save on this, if not could it be made.

Game saves don’t work, maybe snapshots?

**Comment by sezgit** [comment]
like the game saves on the rom, not just saving like snapshots.

**Comment by HTV04** [comment]
Not at the moment. Quick note that this uses an unmodified version of JSNES, which doesn't support saves or save states at the moment. I'm not planning on modifying it for compatibility reasons (if bfirsh releases an update to JSNES, webNES CE gets the update too). If an update release for JSNES that also includes saves and/or save states, I could try to implement this functionality into webNES CE also long as there's an API for it.

Quick question, what specific device are you running webNES CE on?

**Comment by sezgit** [comment]
iOS 12.3.1 iPad 5th gen(this is a school one, not mainly using this one)

Android 7.0 Honor 6X

**Comment by bearcop** [comment]
I found a fork of JSNES with save states while reading on issues

however, it outdated-ish? https://github.com/josephlewis42/jsnes
