### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Conyeucuma** [HTV04/htv04.github.io#16]
Is there a way the sound can play through the speaker of our device?

**Comment by HTV04** [comment]
What device are you using?

**Comment by sezgit** [comment]
Just tried it, looks like it depends
The iPad 5th gen on ios12 has no sound

On the other hand my honor 6x works flawlessly

**Comment by Conyeucuma** [comment]
> Just tried it, looks like it depends
> The iPad 5th gen on ios12 has no sound
> 
> On the other hand my honor 6x works flawlessly

Same

**Comment by HTV04** [comment]
From my understanding, the emulator is working perfectly except for sound? The reason why I'm mentioning this because it seems like iOS 13 added an experimental flag that's enabled by default called "Disable WebSQL," which webNES CE currently relies on (we're trying to move to IndexedDB right now, lol). If the flag isn't disabled, webNES CE doesn't function at all.

**Comment by bearcop** [comment]
this is in ios 12, i may check on that.

Works flawlessly except sound on ios 12 is basically what happening

**Comment by HTV04** [comment]
Try updating to iOS 13 if you can. Remember to change the flag after updating.

**Comment by bearcop** [comment]
Got it, will try soon

**Comment by sezgit** [comment]
Hey all I think I may know the issue

The HTML5 Web Audio API is being used for audio right? Well with some quick researching I think it need to be "unlocked" before using audio


>Within Web Audio API everything happens inside of an AudioContext, an audio-processing graph built from audio nodes linked together, which controls both the creation of the nodes it contains and the execution of the audio processing, or decoding.

>On iOS devices this context is initially suspended (“locked”) and in order to enable sounds on a web page we need to get it out of the suspended state, or “unlock” it, within first user interaction.


You'll need to figure out how to play webaudio on ios

**Comment by HTV04** [comment]
It is unlocked, tested on iOS and Chrome.
